Add config variranle for persistent asana task owner
Asana/SGTM pull request #159
Opened 2023-11-10 19:57 UTC by drewalam-asana

2023-11-13 23:06 UTC, suzyng83209 requested changes
mostly just copy changes

2023-11-13 23:06 UTC, suzyng83209 commented on src/asana/helpers.py
> +from . import logic as asana_logic
ik its there but let's use the absolute import

2023-11-14 19:05 UTC, drewalam-asana commented on README.md
> +* Ensure that the PR has the `task assignee is always pr author` Github label attached to the PR.
- we currently support a dozen or so github labels, and doing some reaserch online doesn't show any real issues. I see some reports of ~15k labels. It just becomes harder to find the correct label. I don't think it's worth investing on a problem that might not happen for a very long time.
- I have a planned PR that will allow you to automatically add this in through git pr. You'll also be able to set it in your git pr config to always append this label to your pr.
- I'll call it TF_VAR_sgtm_feature__allow_persistent_task_assignee

2023-11-15 18:54 UTC, suzyng83209 approved these changes

2023-11-15 19:45 UTC, merged